# Generated by Django 3.2 on 2022-08-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to='videoapi/video')),
                ('video_name', models.CharField(max_length=50)),
                ('video_discription', models.TextField()),
            ],
        ),
    ]
