# Generated by Django 3.2 on 2022-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
