# Generated by Django 3.2 on 2022-08-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0002_video_video_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
