# Generated by Django 3.2 on 2022-09-02 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videostore', '0003_video_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auth.user'),
            preserve_default=False,
        ),
    ]
