# Generated by Django 3.2 on 2022-09-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0005_alter_video_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
    ]
