# Generated by Django 3.2 on 2022-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0007_remove_video_video_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_formate',
            field=models.CharField(choices=[('.mp4', 'MPEG-4'), ('.mov', 'MOV')], default='.mp4', max_length=5),
        ),
    ]
